Repository Ca-moes/RCOM, pull requests merged in 2020-10, with the labels that each got.

#11 llwrite()
  Lab_1/Aula_rest/src/application.c
  Lab_1/Aula_rest/src/macros.h
  Lab_1/Aula_rest/src/pla.c
  Lab_1/Aula_rest/src/progwrite
Labels: enhancement

#12 llwrite() - 2º branch
  Lab_1/Aula_rest/src/application.c
  Lab_1/Aula_rest/src/logs.c
  Lab_1/Aula_rest/src/logs.h
  Lab_1/Aula_rest/src/macros.h
  Lab_1/Aula_rest/src/noncanonical.c
  Lab_1/Aula_rest/src/pla.c
  Lab_1/Aula_rest/src/pla.h
  Lab_1/Aula_rest/src/writenoncanonical.c
Labels: enhancement

#23 Loose Ends
  Lab_1/Aula_rest/src/application.c
  Lab_1/Aula_rest/src/logs.c
  Lab_1/Aula_rest/src/pla.c
  Lab_1/Aula_rest/src/pla.h
  Lab_1/Aula_rest/src/run_read.sh
  Lab_1/Aula_rest/src/run_write.sh
Labels: enhancement

#25 done llclose and fixed log function bug
  Lab_1/Aula_rest/src/application.c
  Lab_1/Aula_rest/src/logs.c
  Lab_1/Aula_rest/src/macros.h
  Lab_1/Aula_rest/src/pla.c
  Lab_1/Aula_rest/src/pla.h
Labels: enhancement

#28 Refactoring PLA
  Lab_1/Aula_rest/docs/flags.txt
  Lab_1/Aula_rest/docs/state_machine_info.c
  Lab_1/Aula_rest/src/application.c
  Lab_1/Aula_rest/src/macros.h
  Lab_1/Aula_rest/src/pla.c
  Lab_1/Aula_rest/src/pla.h
  Lab_1/Aula_rest/src/run_read.sh
  Lab_1/Aula_rest/src/run_write.sh
  Lab_1/Aula_rest/src/statemachine.c
  Lab_1/Aula_rest/src/statemachine.h
Labels: refactoring

#29 Refactoring Cicles
  .vscode/settings.json
  Lab_1/Aula_rest/docs/ciclos_while.txt
  Lab_1/Aula_rest/docs/state_machine_info.c
  Lab_1/Aula_rest/notes/flags.txt
  Lab_1/Aula_rest/src/pla.c
  Lab_1/Aula_rest/src/pla.h
  Lab_1/Aula_rest/src/statemachine.c
  Lab_1/Aula_rest/src/statemachine.h
Labels: refactoring

#30 Application
  Lab_1/Aula_rest/docs/hello
  Lab_1/Aula_rest/docs/pinguim.
  Lab_1/Aula_rest/src/application.c
  Lab_1/Aula_rest/src/hello
  Lab_1/Aula_rest/src/logs.c
  Lab_1/Aula_rest/src/logs.h
  Lab_1/Aula_rest/src/macros.h
  Lab_1/Aula_rest/src/pinguim.gif
  Lab_1/Aula_rest/src/pla.c
  Lab_1/Aula_rest/src/pla.h
  Lab_1/Aula_rest/src/run_read.sh
  Lab_1/Aula_rest/src/run_write.sh
  Lab_1/Aula_rest/src/statemachine.c
Labels: enhancement

#36 Tamanho de array depois de stuffing
  Lab_1/Aula_rest/docs/flags.txt
  Lab_1/Aula_rest/docs/pinguim.gif
  Lab_1/Aula_rest/src/macros.h
  Lab_1/Aula_rest/src/pla.h
Labels: solved

#37 Cortar ligação a meio de envio
  Lab_1/Aula_rest/docs/pinguim.gif
  Lab_1/Aula_rest/src/application.c
  Lab_1/Aula_rest/src/pla.c
Labels: enhancement

#44 checking sequence number on app
  Lab_1/Aula_rest/docs/big.jpg
  Lab_1/Aula_rest/docs/flags.txt
  Lab_1/Aula_rest/docs/pinguim.gif
  Lab_1/Aula_rest/src/application.c
  Lab_1/Aula_rest/src/big.jpg
  Lab_1/Aula_rest/src/dcp.c
  Lab_1/Aula_rest/src/dcp_spec.c
  Lab_1/Aula_rest/src/dcp_spec.h
  Lab_1/Aula_rest/src/macros.h
  Lab_1/Aula_rest/src/run_read.sh
  Lab_1/Aula_rest/src/run_write.sh
  Lab_1/Aula_rest/src/statemachine.c
Labels: enhancement
